title: Async Let
description: "Articles about Swift, iOS and indie projects delivered asynchronously await!"

url: https://www.async-let.com
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/
future: false

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About Me
      url: /about

social:
    github: cameroncooke
    twitter: camsoft2000
    email: hello@cameroncooke.com
    linkedin: cameroncooke1

google_analytics: "G-SF4FBXKHE3"

gisqus:
    repo: cameroncooke/async-let.com
    repo_id: R_kgDOORIzXA
    category: Comments
    category_id: DIC_kwDOORIzXM4CpHQW
    mapping: pathname
    strict: 0
    reactions_enabled: 1
    emit_metadata: 0
    input_position: top
    theme: preferred_color_scheme
    lang: en
    loading: lazy