title: Async Let
description: Long Form Jekyll theme built with SASS

url: https://async-let.com
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about

social:
    github: cameroncooke
    twitter: camsoft2000
    email: web@cameroncooke.com
    linkedin: cameroncooke1

google_analytics: "G-SF4FBXKHE3"
